package ch.aoz.maps;

/**
 * TODO: Insert description here. (generated by vsevolodshorin)
 */
public class Strings {
  public static String[] months_de = {"Januar",
    "Februar",
    "März",
    "April",
    "Mai",
    "Juni",
    "Juli",
    "August",
    "September",
    "Oktober",
    "November",
    "Dezember"};
}
